resource_types:
  - name: docker-swarm-deploy 
    type: docker-image
    source:
      repository: bristechsrm/docker-swarm-deploy
jobs:
- name: build
  public: true
  serial: true
  plan:
  - aggregate:
    - get: sessions-trigger
      trigger: true
    - get: code
      trigger: true
  - put: image
    params:
      build: code
  - put: swarm

resources:
- name: code
  type: git
  source:
    uri: https://github.com/BristechSRM/api-docs.git

- name: sessions-trigger
  type: git
  source:
    uri: https://github.com/BristechSRM/sessions.git
    paths: Sessions/api.json

- name: image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: bristechsrm
    password: {{docker-hub-password}}
    repository: bristechsrm/api_docs

- name: swarm
  type: docker-swarm-deploy
  source:
    serviceName: api-docs
    nodeName: api-docs
    repository: bristechsrm/api_docs
    swarmMasterIp: {{swarmMasterIp}}
    overlay: overlay
    accessKeyId: {{awsAccessKeyId}}
    secretAccessKey: {{awsSecretAccessKey}}
